### ISSUE TITLE
Issue : ovh.exceptions.InvalidRegion

### ISSUE THREAD

**Issue by kaizeneziak** [antoiner77/letsencrypt.sh-ovh#4]
Bonjour,

J'ai télécharger votre hook afin de le faire fonctionner avec [Dehydrated](https://github.com/lukas2511/dehydrated.git) et je rencontre l'erreur suivante : 

```
# ./dehydrated -c
# INFO: Using main config file /opt/dehydrated/config
Processing william-feo.fr with alternative names: www.william-feo.fr
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for william-feo.fr...
 + Requesting challenge for www.william-feo.fr...
Traceback (most recent call last):
  File "hooks/ovh/ovhdns.py", line 32, in <module>
    client = ovh.Client()
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 159, in __init__
    endpoint, ENDPOINTS.keys())
ovh.exceptions.InvalidRegion: ('Unknow endpoint %s. Valid endpoints: %s', None, ['kimsufi-ca', 'kimsufi-eu', 'soyoustart-eu', 'ovh-ca', 'ovh-eu', 'runabove-ca', 'soyoustart-ca'])
```

Ne connaissant pas le langage Python, je ne vois pas où se situe l'erreur. 

De plus pour l'exécution du script dehydrated, j'ai créer une copie du fichier **ovh.conf.demo** en **ovh.conf** en renseignant les paramètres demandés.

**Comment by antoinerrr** [comment]
Salut,
Peux tu poster ton .conf ici (en retirant bien tes token)
merci

**Comment by kaizeneziak** [comment]
Salut,

Merci pour ton retour rapide. Voici mes fichiers de configurations détaillés ci-dessous.
Le fichier **/opt/dehydrated/hooks/ovh/ovh.conf** : 

```
[default]
; general configuration: default endpoint
endpoint=ovh-eu

[ovh-eu]
; configuration specific to 'ovh-eu' endpoint
application_key=[application_key]
application_secret=[application_secret]
; uncomment following line when writing a script application
; with a single consumer key.
consumer_key=[consumer_key]
```

Les champs **[application_key]**, **[application_secret]** et **[consumer_key]** ne sont pas entre guillemets ou apostrophes.

Le fichier **/opt/dehydrated/config** : 

```
#!/usr/bin/env bash

CHALLENGETYPE="dns-01"
HOOK="/opt/dehydrated/hooks/ovh/ovhdns.py"

WELLKNOWN="/var/www/dehydrated"

# Algorithme ECDSA
KEY_ALGO=secp384r1

# Fichier des domaines
DOMAINS_TXT="/opt/dehydrated/domains.txt"

# E-mail to use during the registration (default: <unset>)
CONTACT_EMAIL="contact@william-feo.fr"
```

J'ai défini la variable **[KEY_ALGO]** sur **secp384r1** pour obtenir un certificat ECDSA.

Le fichier /opt/dehydrated/domains.txt : 

`william-feo.fr www.william-feo.fr`

**Comment by antoinerrr** [comment]
Tu peux essayer de remplacer les lignes 32 et 48 par

```
client = ovh.Client(
    endpoint='ovh-eu',
    application_key='application key',
    application_secret='application secret',
    consumer_key='consumer key',
)
```

en y ajoutant tes tokens
Attention a l'indentation (tout au meme niveau, espace et pas de TAB)

**Comment by kaizeneziak** [comment]
Je ne peux malheureusement plus vérifier le problème pour le moment. Je fais un retour dès que je le peux.

**Comment by ghost** [comment]
Bonjour,

Je confirme le problème de @kaizeneziak avec dehydrated.
La solution de @antoiner77 fonctionne.

Merci

**Comment by antoinerrr** [comment]
Je vais essayer de faire une update du script a l'occasion, pas l'occasion de le réutiliser pour le moment.
Merci pour la confirmation
