### ISSUE TITLE
Pb with sub-subdomains

### ISSUE THREAD

**Issue by niko44** [antoiner77/letsencrypt.sh-ovh#5]
Hy,

I encoutered an issue when I want to make a dns01-chanllenge with sub-subdomain. Ie: I wanna have one certificate for xxx.yyy.mydomain.com, but I have this : 

```
Processing xxx.yyy.mydomain.com
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for xxx.yyy.mydomain.com...
Traceback (most recent call last):
  File "/opt/hook_ovh/ovhdns.py", line 37, in <module>
    target=token
  File "/usr/lib/python2.7/site-packages/ovh/client.py", line 371, in post
    return self.call('POST', _target, kwargs, _need_auth)
  File "/usr/lib/python2.7/site-packages/ovh/client.py", line 472, in call
    response=result)
ovh.exceptions.ResourceNotFoundError: This service does not exist
```

For your information, I suspect the pb corresponding between lines 26-31...

**Comment by antoinerrr** [comment]
Hi,
This script only works with xxx.domain.com or domain.com, You need to make some changes on the code if you want to use yyy.xxx.domain.com :/  I have no time right now sorry

**Comment by niko44** [comment]
Thks for your reply. Of course, I understand! 
I take a look on it and I keep you informed.

**Comment by antoinerrr** [comment]
#6
